sudo: false

language: python

addons:
  firefox: "59.0.2"

python:
   - "3.6"

before_install:
    - cat .travis.yml
    - pip install --upgrade pip
    - pip --version

install:
    - pip install -r requirements.txt
    - pip list

before_script:
    - date
    - uname -a
    - printenv | sort
    - cat requirements.txt
    - git       --version
    - make      --version
    - python3.6 --version
    - ls -al
    - cat makefile

script:
    - make travis

notifications:
    slack: cs373-group10:wW0GSRNiXUC2f6VfRnM6DXsJ